{"name": "test_login_none_existing_user", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message:", "trace": "self = <test_login_negative.TestLoginNegative object at 0x000002019F882A40>\n\n    @pytest.mark.tcid12\n    def test_login_none_existing_user(self):\n    \n        my_account = MyAccountSignOut(self.driver)\n        my_account.go_to_my_account()\n        my_account.input_login_username('asfgwlekj')\n        my_account.input_login_password('asdvwger')\n        my_account.click_login_button()\n    \n        # verify error message\n        expected_err = 'Unknown username. Check again or try your email address.'\n>       my_account.wait_until_error_is_displayed(expected_err)\n\nqatest\\tests\\my_account\\test_login_negative.py:19: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nqatest\\src\\pages\\MyAccountSignOut.py:34: in wait_until_error_is_displayed\n    self.sl. wait_until_element_contains_text(self.ERROR_UL,exp_err)\nqatest\\src\\SeleniumExtended.py:34: in wait_until_element_contains_text\n    WebDriverWait(self.driver, timeout).until(\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"2829a51cf83799290026530439f5f7ec\")>\nmethod = <function text_to_be_present_in_element.<locals>._predicate at 0x000002019F8AADD0>, message = ''\n\n    def until(self, method, message=''):\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.time() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except InvalidSelectorException as e:\n                raise e\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, 'screen', None)\n                stacktrace = getattr(exc, 'stacktrace', None)\n            time.sleep(self._poll)\n            if time.time() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message:\n\n..\\PycharmProjects\\Python-Selenium-Course\\python_selenium_course_material\\SELENIUM_SECTION\\test_env\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py:89: TimeoutException"}, "start": 1648837380137, "stop": 1648837392475, "uuid": "471b8b85-b863-48a9-beba-49b8807dd9e9", "historyId": "3b923004665eea39b536ed74517924ae", "testCaseId": "21a4a96dc547e68d9b797278d1c8b6ae", "fullName": "qatest.tests.my_account.test_login_negative.TestLoginNegative#test_login_none_existing_user", "labels": [{"name": "tag", "value": "tcid12"}, {"name": "tag", "value": "@pytest.mark.usefixtures('init_driver')"}, {"name": "parentSuite", "value": "qatest.tests.my_account"}, {"name": "suite", "value": "test_login_negative"}, {"name": "subSuite", "value": "TestLoginNegative"}, {"name": "host", "value": "DESKTOP-G3LLG73"}, {"name": "thread", "value": "15428-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "qatest.tests.my_account.test_login_negative"}]}